<br/>
<nav class="navbar navbar-expand-lg  navbar-light style="background-color: #fbc7d4;"">
    <a class="navbar-brand" href="index.php">Meus Exercícios</a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="index.php"> Listagem
                <span class="sr-only">(current)</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="https://github.com/RDiasMartins"> Perfil GitHub</a>
        </li>
    </ul>
</nav>
